import Header from '@/components/shared/Header';
import './globals.css';

export const metadata = {
  title: 'imdb By ahemd ashraf',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        {/* Header */}
        <Header />
        {/* Navbar */}
        {/* Search */}
        {children}
      </body>
    </html>
  );
}
