import Header from '@/components/shared/Header';
import Navbar from '@/components/shared/Navbar';
import SearchBox from '@/components/shared/SearchBox';
import './globals.css';
import Providers from './Providers';

export const metadata = {
  title: 'imdb By ahemd ashraf',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          {/* Header */}
          <Header />
          {/* Navbar */}
          <Navbar />
          {/* Search */}
          <SearchBox />
          {children}
        </Providers>
      </body>
    </html>
  );
}
